hydra:
  job:
    chdir: True
run:
  train: True
  test: True
  viz: False
  experiment: default
  mlflow_on: False
  mlflow_uri: /path/to/mlflow/db
  seed: 42
  cudnn_benchmark: False
  set_deterministic: True
  checkpoint_model: ""
  checkpoint_params: ""
  base_shape_dir: ../base_shapes/
train:
  epochs: 200
  workers: 8
  lr: 4e-5
  lr_scheduler: plateau
  lr_min: 0.
  n_annealing: 1
  lr_patience: 11  # Only used with plateau lr scheduler
  lr_threshold: 0.1  # Only used with plateau lr scheduler
  batch_size: 3
  batch_size_test: 10
  valid_epoch_interval: 1
  mpjpe_epoch_interval: 5
  flip_aug: True
  tta: True
  sq_loss: False  # whether to use squared L2 loss instead of L2 loss
  w_loss: True  # whether to weight joints in the loss
  vel_loss: 2.  # weight of velocity loss
  smooth_reg: 0.5  # weight of smoothness regularization
  rmcl_score_reg: 0.1  # beta weight for score regularization in rMCL
  rigid_seg_reg: 0.0  # weight of rigid segments regularization
  lat_sym_regularization: 0.0  # weight of lateral symmetry regularization
multi_hyp:
  n_hyp: 5
  agg_strategy: average
model:
  arch: rmcl_manifold
  layers: 8
  channels: 512
  nheads: 8
  rot_dim: 6
  layers_seg: 2
  channels_seg: 128
  nheads_seg: 8
  drop_path_rate: 0.1
  mup: False  # whether to use mu parametrization
data:
  joints: 17
  miss_rate: 0.2
  miss_type: no_miss  # options are 'no_miss', 'random', 'random_left_arm_right_leg', 'structured_joint', 'structured_frame', 'noisy'
  noise_sigma: 5
  data: all
  data_dir: /path/to/data/
  dataset: h36m  # target dataset
  keypoints: cpn_ft_h36m_dbb  # 2D detections to use
  actions: '*'  # actions to train/test on, separated by comma, or * for all
  use_valid: False  # Whether to use a vliadation set
  seq_len: 243
viz:
  viz_subject: S11
  viz_action: greeting  # directions,discussion,eating,greeting,phoning,posing,purchases,sitting,sittingdown,smoking,photo,waiting,walking,walkdog,walktogether
  viz_camera: 0
  viz_video: ""
  viz_skip: 0  # skip first N frames of input video
  viz_output: ""  # output file name (.gif or .mp4)
  viz_bitrate: 3000  # bitrate for mp4 videos
  viz_limit: 1000  # only render first N frames (-1 to render all video)
  viz_downsample: 1  # downsample FPS by a factor N
  viz_size: 5  # image size
  extension: mp4
  hypothesis: True
  azim: ""
  azim_max: ""
  stationary_frames: 50
  elev: ""
  frame_index: -1  # if > -1, will only render a single frame of this index